title = "Vlad Svitlychnyi"
description = "A Linux geek from Ukraine who lives in Poland"

# The URL the site will be built for
base_url = "https://vsv.dev"
theme = "anpu"

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
anpu_menu_links = [
    { url = "$BASE_URL/resume/", name = "Resume" },
    { url = "$BASE_URL/about/", name = "About" },
]
anpu_author = "Vlad Svitlychnyi"
