# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v3.0.0
    # Build & deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        # Target branch
        PAGES_BRANCH: gh-pages
        # Provide personal access token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
